package com.mycompany.atm;

import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JPanel;

/**
 *
 * @author Vee Pabuence
 */
public class IngresarDinero extends javax.swing.JPanel {
    int id_cliente;
    JPanel contenedorPN = new JPanel();
    
    /**
     * Creates new form IngresarDinero
     */
    public IngresarDinero(int ID, JPanel pn) {
        initComponents();
        id_cliente = ID;
        contenedorPN = pn;
        setSize(800, 460);
        setVisible(true);

        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/bd_atm", "vee", "123");
            PreparedStatement pst2 = cn.prepareStatement("SELECT * FROM lista_clientes WHERE ID = " + id_cliente);
            ResultSet rs = pst2.executeQuery();

            if (rs.next()) {
                label_nombre.setText(label_nombre.getText() + rs.getString("Nombre"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        text_ingresar = new javax.swing.JTextField();
        btn_Cancelar = new javax.swing.JButton();
        btn_Aceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_nombre.setText("Hola ");
        add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Cúanto vas a ingresar?: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        text_ingresar.setBackground(new java.awt.Color(204, 204, 204));
        text_ingresar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        text_ingresar.setForeground(new java.awt.Color(0, 0, 0));
        text_ingresar.setBorder(null);
        text_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ingresarActionPerformed(evt);
            }
        });
        text_ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_ingresarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_ingresarKeyReleased(evt);
            }
        });
        add(text_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 270, 50));

        btn_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cancelar.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        btn_Cancelar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setBorder(null);
        btn_Cancelar.setBorderPainted(false);
        btn_Cancelar.setContentAreaFilled(false);
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 170, 40));

        btn_Aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Aceptar.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        btn_Aceptar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.setBorder(null);
        btn_Aceptar.setBorderPainted(false);
        btn_Aceptar.setContentAreaFilled(false);
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 170, 40));

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ingreso de dinero al ATM de Bambolonvia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void text_ingresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_ingresarKeyPressed
    }//GEN-LAST:event_text_ingresarKeyPressed

    private void text_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ingresarActionPerformed
    }//GEN-LAST:event_text_ingresarActionPerformed

    private void text_ingresarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_ingresarKeyReleased
        try {
            if (Character.getNumericValue(text_ingresar.getText().charAt(text_ingresar.getText().length() - 1)) >= 0 && Character.getNumericValue(text_ingresar.getText().charAt(text_ingresar.getText().length() - 1)) <= 9) {
            } else {
                JOptionPane.showMessageDialog(null, "ERROR, no se aceptan caracteres, solo numeros.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_text_ingresarKeyReleased

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        Menu v1 = new Menu(contenedorPN);
        
        contenedorPN.removeAll();
        contenedorPN.setLocation(0, 0);
        contenedorPN.setSize(800,460);
        contenedorPN.add(v1);
        contenedorPN.revalidate();
        contenedorPN.repaint();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas segure que quieres ingresar "+text_ingresar.getText()+"$?");
        int Saldo;
        
        if (confirmacion == 0) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/bd_atm", "vee", "123");
                PreparedStatement pst2 = cn.prepareStatement("SELECT * FROM lista_clientes WHERE ID = " + id_cliente);
                ResultSet rs = pst2.executeQuery();

                if (rs.next()) {
                    Saldo = Integer.parseInt(rs.getString("Saldo")) + Integer.parseInt(text_ingresar.getText());
                    PreparedStatement pst = cn.prepareStatement("UPDATE lista_clientes set Saldo = ? WHERE ID = " + id_cliente);

                    pst.setString(1, String.valueOf(Saldo));
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Actualización exitosa.");
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR, intenta nuevamente");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        } else if (confirmacion == 2) {
            Menu v1 = new Menu(contenedorPN);

            contenedorPN.removeAll();
            contenedorPN.setLocation(0, 0);
            contenedorPN.setSize(800, 460);
            contenedorPN.add(v1);
            contenedorPN.revalidate();
            contenedorPN.repaint();
        }
    }//GEN-LAST:event_btn_AceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField text_ingresar;
    // End of variables declaration//GEN-END:variables
}
