/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vee Pabuence
 */
public class RetirarDinero extends javax.swing.JPanel {
    int id_cliente;
    JPanel contenedorPN = new JPanel();
    /**
     * Creates new form RetirarDinero
     */
    public RetirarDinero(int ID, JPanel pn) {
        initComponents();
        id_cliente = ID;
        contenedorPN = pn;
        setSize(800, 460);
        setVisible(true);
        
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/bd_atm", "vee", "123");
            PreparedStatement pst2 = cn.prepareStatement("SELECT * FROM lista_clientes WHERE ID = " + id_cliente);
            ResultSet rs = pst2.executeQuery();
            if (rs.next()) {
                label_nombre.setText(label_nombre.getText() + rs.getString("Nombre"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        text_ingresar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Retiro de dinero del ATM de Bambolonvia");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        label_nombre.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_nombre.setText("Hola ");
        add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Cúanto vas a retirar?: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        text_ingresar.setBackground(new java.awt.Color(204, 204, 204));
        text_ingresar.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        text_ingresar.setForeground(new java.awt.Color(0, 0, 0));
        text_ingresar.setBorder(null);
        text_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ingresarActionPerformed(evt);
            }
        });
        text_ingresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_ingresarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_ingresarKeyReleased(evt);
            }
        });
        add(text_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 270, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void text_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ingresarActionPerformed

    }//GEN-LAST:event_text_ingresarActionPerformed

    private void text_ingresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_ingresarKeyPressed

    }//GEN-LAST:event_text_ingresarKeyPressed

    private void text_ingresarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_ingresarKeyReleased
        try {
            if (Character.getNumericValue(text_ingresar.getText().charAt(text_ingresar.getText().length() - 1)) >= 0 && Character.getNumericValue(text_ingresar.getText().charAt(text_ingresar.getText().length() - 1)) <= 9) {
            } else {
                JOptionPane.showMessageDialog(null, "ERROR, no se aceptan caracteres, solo numeros.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_text_ingresarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTextField text_ingresar;
    // End of variables declaration//GEN-END:variables
}
