package com.mycompany.atm;

import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JOptionPane;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

/**
 *
 * @author Vee Pabuence
 */
public class ValidacionATM extends javax.swing.JPanel {   
    List<JButton> botones = new ArrayList<>();
    JPanel contenedorPN = new JPanel();
    int validacionPantalla;
    
    
    public ValidacionATM(JPanel pn, int nextWindow) {
        initComponents();
        contenedorPN = pn;
        validacionPantalla = nextWindow;
        setSize(800,460);
        setVisible(true);
        llenarMatriz();
        rellenarNumeros();
    }
    
    public void llenarMatriz(){
        botones.add(jButton1);
        botones.add(jButton2);
        botones.add(jButton3);
        botones.add(jButton3);
        botones.add(jButton4);
        botones.add(jButton5);
        botones.add(jButton6);
        botones.add(jButton7);
        botones.add(jButton8);
        botones.add(jButton9);
        botones.add(jButton10);
    }
    
    public void rellenarNumeros(){
        int numRan, iterador;
        boolean bandera;
        for (int i = 1; i < 11; i++) {
            bandera = true;
            do {
                iterador=0;
                numRan = (int) ((Math.random() * (10 - 0)) + 0);
                for (int j = 1; j < 11; j++) {
                    if (numRan == Integer.parseInt(botones.get(j).getText())) {
                        break;
                    }
                    else{
                        iterador++;
                    }
                }
                if (iterador==10) {
                    bandera=false;
                    botones.get(i).setText(String.valueOf(numRan));
                }
            } while (bandera);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        campo_Clave = new javax.swing.JPasswordField();
        campo_ID = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        btn_enter = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingresa tu codigo ID del banco:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel2.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresa tu clave del banco:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Validación ATM de Bambolonvia");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jButton1.setText("0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 40, 40));

        jButton2.setText("0");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 40, 40));

        jButton3.setText("0");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 40, 40));

        jButton4.setText("0");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 40, 40));

        jButton5.setText("0");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 40, 40));

        jButton6.setText("0");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 40, 40));

        jButton7.setText("0");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 40, 40));

        jButton8.setText("0");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 40, 40));

        jButton9.setText("0");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 40, 40));

        btn_borrar.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 90, 40));

        campo_Clave.setEditable(false);
        campo_Clave.setBackground(new java.awt.Color(204, 204, 204));
        campo_Clave.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        campo_Clave.setForeground(new java.awt.Color(0, 0, 0));
        campo_Clave.setBorder(null);
        campo_Clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_ClaveKeyTyped(evt);
            }
        });
        add(campo_Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 180, 40));

        campo_ID.setEditable(false);
        campo_ID.setBackground(new java.awt.Color(204, 204, 204));
        campo_ID.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        campo_ID.setForeground(new java.awt.Color(0, 0, 0));
        campo_ID.setBorder(null);
        campo_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_IDActionPerformed(evt);
            }
        });
        campo_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_IDKeyTyped(evt);
            }
        });
        add(campo_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 180, 40));

        jButton10.setText("0");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 40, 40));

        btn_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(0, 0, 0));
        btn_ingresar.setText("Ingresar...");
        btn_ingresar.setBorder(null);
        btn_ingresar.setBorderPainted(false);
        btn_ingresar.setContentAreaFilled(false);
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 170, 40));

        btn_enter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_enter.setText("Enter");
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 90, 40));

        btn_regresar.setBackground(new java.awt.Color(255, 255, 255));
        btn_regresar.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        btn_regresar.setForeground(new java.awt.Color(0, 0, 0));
        btn_regresar.setText("Regresar...");
        btn_regresar.setBorder(null);
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 170, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void campo_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_IDActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        if (campo_Clave.getText().length() == 4) {
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/bd_atm", "vee", "123");
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM lista_clientes WHERE ID = ?");

                try {
                    final String claveEncriptacion = "Never gonna give you up, never gonna let you down";
                    String datosOriginalesID = campo_ID.getText();
                    String datosOriginalesClave = campo_Clave.getText();

                    encriptadoAES encriptador = new encriptadoAES();
                    String encriptadoID = encriptador.encriptar(datosOriginalesID, claveEncriptacion);
                    String encriptadoClave = encriptador.encriptar(datosOriginalesClave, claveEncriptacion);
                    
                    System.out.println(encriptadoClave);
                    System.out.println(encriptadoID);

                    pst.setString(1, encriptadoID);

                    ResultSet rs = pst.executeQuery();

                    pst = cn.prepareStatement("SELECT * FROM lista_clientes WHERE Clave = ?");
                    pst.setString(1, encriptadoClave);

                    ResultSet rs2 = pst.executeQuery();

                    if (rs.next() && rs2.next()) {
                        nextWindow(validacionPantalla);
                    } else {
                        JOptionPane.showMessageDialog(null, "No existe dicha ID o contraseña incorrecta.");
                    }

                } catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                    Logger.getLogger(encriptadoAES.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "La clave debe de ser 4 digitos");
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    public void nextWindow(int nextWindow) {
        if (nextWindow == 0) {
            IngresarDinero addCash = new IngresarDinero(Integer.parseInt(campo_ID.getText()), contenedorPN);

            contenedorPN.removeAll();
            contenedorPN.setLocation(0, 0);
            contenedorPN.setSize(800, 460);
            contenedorPN.add(addCash);
            contenedorPN.revalidate();
            contenedorPN.repaint();
        } else if (nextWindow == 1) {
            RetirarDinero withdrawCash = new RetirarDinero(Integer.parseInt(campo_ID.getText()), contenedorPN);

            contenedorPN.removeAll();
            contenedorPN.setLocation(0, 0);
            contenedorPN.setSize(800, 460);
            contenedorPN.add(withdrawCash);
            contenedorPN.revalidate();
            contenedorPN.repaint();
        } else if (nextWindow == 2) {
            VerSaldo vs = new VerSaldo(Integer.parseInt(campo_ID.getText()), contenedorPN);

            contenedorPN.removeAll();
            contenedorPN.setLocation(0, 0);
            contenedorPN.setSize(800, 460);
            contenedorPN.add(vs);
            contenedorPN.revalidate();
            contenedorPN.repaint();
        }
        else if (nextWindow==3) {
            VerMovimientos vm = new VerMovimientos(Integer.parseInt(campo_ID.getText()), contenedorPN);
            
            contenedorPN.removeAll();
            contenedorPN.setLocation(0, 0);
            contenedorPN.setSize(800, 460);
            contenedorPN.add(vm);
            contenedorPN.revalidate();
            contenedorPN.repaint();
        }
        else{
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, intenta nuevamente.");
        }
    }
    
    boolean banderaCampos = true;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton2.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton2.getText());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton5.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton5.getText());
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton3.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton3.getText());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton1.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton1.getText());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton4.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton4.getText());
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton6.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton6.getText());
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton10.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton10.getText());
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton7.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton7.getText());
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton8.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton8.getText());
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (banderaCampos) {
            if (campo_ID.getText().length() < 10) {
                campo_ID.setText(campo_ID.getText()+jButton9.getText());
            }
        }
        else{
            if (campo_Clave.getText().length() < 4) {
                campo_Clave.setText(campo_Clave.getText()+jButton9.getText());
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        campo_Clave.setText("");
        campo_ID.setText("");
        banderaCampos=true;
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
        banderaCampos=false;
    }//GEN-LAST:event_btn_enterActionPerformed

    private void campo_ClaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_ClaveKeyTyped
        if (campo_Clave.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_ClaveKeyTyped

    private void campo_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_IDKeyTyped
        if (campo_ID.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_campo_IDKeyTyped

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Menu v1 = new Menu(contenedorPN);
        
        contenedorPN.removeAll();
        contenedorPN.setLocation(0, 0);
        contenedorPN.setSize(800,460);
        contenedorPN.add(v1);
        contenedorPN.revalidate();
        contenedorPN.repaint();
    }//GEN-LAST:event_btn_regresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_enter;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPasswordField campo_Clave;
    private javax.swing.JPasswordField campo_ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
