/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.atm;

import java.sql.*;
import javax.swing.JPanel;

/**
 *
 * @author Vee Pabuence
 */
public class VerMovimientos extends javax.swing.JPanel {
    String id_cliente;
    JPanel contenedorPN = new JPanel();
    /**
     * Creates new form VerMovimientos
     */
    public VerMovimientos(String ID, JPanel pn) {
        initComponents();
        id_cliente = ID;
        contenedorPN = pn;
        setSize(800, 460);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Cancelar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_Cancelar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Cancelar1.setFont(new java.awt.Font("Unispace", 2, 14)); // NOI18N
        btn_Cancelar1.setForeground(new java.awt.Color(0, 0, 0));
        btn_Cancelar1.setText("Cancelar");
        btn_Cancelar1.setBorder(null);
        btn_Cancelar1.setBorderPainted(false);
        btn_Cancelar1.setContentAreaFilled(false);
        btn_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(btn_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(327, Short.MAX_VALUE)
                .addComponent(btn_Cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancelar1ActionPerformed
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3308/bd_atm", "vee", "123");
            PreparedStatement pst = cn.prepareStatement("CREATE TABLE IF NOT EXISTS `mydb`.`movimientos_Vee` (\n"
                    + "  `ID` INT NOT NULL,\n"
                    + "  `Fecha` DATETIME NOT NULL,\n"
                    + "  `Ingresos y retiros` INT NOT NULL,\n"
                    + "  `Saldo total` INT NOT NULL,\n"
                    + "  `Created_by` INT NOT NULL,\n"
                    + "  PRIMARY KEY (`ID`),\n"
                    + "  INDEX `Created_by_idx` (`Created_by` ASC) VISIBLE,\n"
                    + "  CONSTRAINT `Created_by`\n"
                    + "    FOREIGN KEY (`Created_by`)\n"
                    + "    REFERENCES `mydb`.`lista_clientes` (`ID`)\n"
                    + "    ON DELETE NO ACTION\n"
                    + "    ON UPDATE NO ACTION)\n"
                    + "ENGINE = InnoDB");

            pst.execute();
            System.out.println("KASJDMASD");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_Cancelar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar1;
    // End of variables declaration//GEN-END:variables
}
